### ISSUE TITLE
Change the name?

### ISSUE THREAD

**Issue by rreusser** [scijs/ndarray-lup-factorization#1]
@Planeshifter — sorry for the conflict (seriously, what are the chances? Within five minutes at 3AM on a Wednesday night we both get the bright idea to push a new LUP factorization repo?), but should I take over the name? No preference on my part beyond just getting something strong out there. I added the two variants (A===L) to this version but don't have non-in-place implemented (which I think should probably just require you to copy if that's what you want—maybe we could standardize this as an optional copy flag that just copies the whole thing and then does in-place if that's what you really want.)

Anyway, I'm open to anything that's forward progress. No territorial stuff here. So I can change the name and omit the -2 suffix or we can hold off. Or merge. Or anything. :smile:

**Comment by Planeshifter** [comment]
Let me delete the other repo and then you can drop the two from the name here. You would need to unpublish from npm and then republish under the new name. Sounds like a plan?
Personally, I think it would be good to have an option to carry out the operations not in-place by making a copy of the input array. While I understand Mikola's performance concerns, I believe it would be more convenient in cases in which you do not mind the cost of making a copy.

**Comment by rreusser** [comment]
Perfect! Thanks! Out at the moment but will follow up ASAP!

## 

Ricky Reusser

**Comment by Planeshifter** [comment]
Deleted the other repo. So consensus with regards to error handling is that we throw if input arguments do not conform to requirements and silently fail and return `false` whenever an algorithm fails to calculate a solution?

**Comment by rreusser** [comment]
Great! And yeah, I think it's a sensible approach, although null or NaN or whatever are also valid. I think clarity and consistency are the important part. I'm flexible. Currently rolling this stuff around in my head and thinking about how and which parts to codify into a style guide.

## 

Ricky Reusser

**Comment by mikolalysenko** [comment]
+1 for just returning false on failure, though again judgement is important.  Sometimes null or NaN makes more sense.
